### PR TITLE
[ObjectsTable] Fix pagination next/prev

### LINKED ISSUE #10: ObjectsTable improvements
From https://github.com/EyeSeeTea/metadata-synchronization/pull/21

- [x] Fix pagination -> #11 

High Priority
- [x] ObjectsTable: Hide checkboxes if there are no fields with multiple set to true.
- [x] Apply branch fix/calculate-page-value
- [x] ObjectsTable: We have `initialSorting` as a required prop, make it optional and assume first sortable column ASC is the default order.
- [x] Update readme for ObjectsTable with explanation regarding prop 'key' to update it.

Low Priority
- [x] Reduce marginTop by 10px, too much space.
- [x] Change model prop to optional (See https://github.com/EyeSeeTea/metadata-synchronization/issues/7 -> Remove model prop from instance-configurator)
- [x] Hide details panel if table refreshes otherwise it can be confusing for the user.

### PR DESCRIPTION
**Pull request by tokland**
Fixes #10 -> Fix pagination

The old code was expecting a D2 pager (with `hasNextPage`/`hasPreviousPage`). Now we simply calculate the values from the current page / max page.

(Not yet published, will do after PRs approved & merged)

### CODE REVIEW

**Review by SferaDev — APPROVED** [review]

**Comment by SferaDev** [comment]
Looks good to me, to simplify it even more we could also calculate (and not require the field) the pageCount as it's always Math.ceil(total / pageSize). What do you think @tokland ?

File: src/objects-table/ObjectsTable.js [hunk 1]
```diff
@@ -199,12 +199,17 @@ class ObjectsTable extends React.Component {
...
 
     getPaginationProps() {
-        const currentlyShown = calculatePageValue(this.state.pager, this.props.pageSize);
         const { pager } = this.state;
 
+        const isValidPage = _(["page", "total"])
+            .difference(_.keys(pager || {}))
+            .isEmpty();
+        if (!isValidPage) return {};
+        const pageCount = Math.ceil(pager.total / pager.pageSize);
```
Comment (SferaDev) [inline src/objects-table/ObjectsTable.js:208]: It should be this.props.pageSize, right?

Comment (tokland) [reply src/objects-table/ObjectsTable.js:208]: Right! It was working for me because I do have pageSize also on the pager, but should get from props. I'll push to dev.

**Comment by tokland** [comment]
d2-ui-components 0.0.9 published. Note that there is a delay on the webpage (it will show 0.0.8 for some minutes), but it should already be on the npm registry ready to be used.
